lutrin_api/venv/bin/python3: can't open file '/home/afornerot/cadoles/lutrin-projet/lutrin/server.py': [Errno 2] No such file or directory
lutrin_api/venv/bin/python3: can't open file '/home/afornerot/cadoles/lutrin-projet/lutrin/server.py': [Errno 2] No such file or directory
Serveur Lutrin Pi démarré. Tesseract CMD: /usr/bin/tesseract
